# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/adventures_with_pi.xdc

# Block Designs: C:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: C:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: C:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: C:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_ps7_0_axi_periph_1/design_1_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_1 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_1} -quiet] -quiet

# IP: C:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_1/design_1_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_1 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_1} -quiet] -quiet

# IP: C:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_zed_audio_ctrl_0_0/design_1_zed_audio_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zed_audio_ctrl_0_0 || ORIG_REF_NAME==design_1_zed_audio_ctrl_0_0} -quiet] -quiet

# IP: C:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: C:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_1 || ORIG_REF_NAME==design_1_xbar_1} -quiet] -quiet

# IP: C:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_axi_mem_intercon_0/design_1_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_0 || ORIG_REF_NAME==design_1_axi_mem_intercon_0} -quiet] -quiet

# IP: C:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_1/design_1_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_1 || ORIG_REF_NAME==design_1_axi_gpio_1_1} -quiet] -quiet

# IP: C:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_3/design_1_rst_ps7_0_100M_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_3 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_3} -quiet] -quiet

# IP: C:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_vga_controller_0_1/design_1_vga_controller_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_vga_controller_0_1 || ORIG_REF_NAME==design_1_vga_controller_0_1} -quiet] -quiet

# IP: C:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_2/design_1_clk_wiz_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_2 || ORIG_REF_NAME==design_1_clk_wiz_0_2} -quiet] -quiet

# IP: C:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: C:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: c:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_rand_num_generator_1_0/design_1_rand_num_generator_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rand_num_generator_1_0 || ORIG_REF_NAME==design_1_rand_num_generator_1_0} -quiet] -quiet

# IP: c:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_xfft_0_0/design_1_xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xfft_0_0 || ORIG_REF_NAME==design_1_xfft_0_0} -quiet] -quiet

# IP: c:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_edge_detect_0_0/design_1_edge_detect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_edge_detect_0_0 || ORIG_REF_NAME==design_1_edge_detect_0_0} -quiet] -quiet

# IP: c:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_0 || ORIG_REF_NAME==design_1_axi_gpio_2_0} -quiet] -quiet

# IP: c:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/design_1_axi_dma_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_0 || ORIG_REF_NAME==design_1_axi_dma_1_0} -quiet] -quiet

# IP: c:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: c:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_xlconcat_1_0/design_1_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_1_0 || ORIG_REF_NAME==design_1_xlconcat_1_0} -quiet] -quiet

# IP: c:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: c:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: c:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] -quiet

# IP: c:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1} -quiet] -quiet

# IP: c:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/dkeum/Downloads/ENSC452-latest_working_audio_vga_code_v3/vivado_latest_block_diagram/audio_tutorial.gen/sources_1/bd/design_1/design_1_ooc.xdc
