webtalk_init -webtalk_dir C:/Users/dkeum/audio_tutorial/CustomIP_test/CustomIP_test.sim/sim_1/behav/xsim/xsim.dir/tb_pseudorng_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb 20 17:21:45 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211630819_1777540226_210757615_661" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "69ea1bae-aa15-467f-90b5-66188325d6e0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0516d566243f4433a08edd97ccbb9b22" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7960_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2662242854 -regid "211630819_1777540226_210757615_661" -xml C:/Users/dkeum/audio_tutorial/CustomIP_test/CustomIP_test.sim/sim_1/behav/xsim/xsim.dir/tb_pseudorng_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/dkeum/audio_tutorial/CustomIP_test/CustomIP_test.sim/sim_1/behav/xsim/xsim.dir/tb_pseudorng_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/dkeum/audio_tutorial/CustomIP_test/CustomIP_test.sim/sim_1/behav/xsim/xsim.dir/tb_pseudorng_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
